version: '3'
services:
  sql-server-db:
    image: mcmoe/mssqldocker
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - sample:/data/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      SA_PASSWORD: 2astazeY
      MSSQL_DB: TESTDB
      MSSQL_USER: brokenbrains
      MSSQL_PASSWORD: 7ellowEl7akey
  customer-service:
    build: ./customer-service
    volumes:
      - sample:/data/services
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
    depends_on:
      - sql-server-db
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sql-server-db:1433;databaseName=TESTDB
  # end container
  account-service:
    build: ./account-service
    volumes:
      - sample:/data/services
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
    ports:
      - "8081:8080"
    depends_on:
      - sql-server-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sql-server-db;databaseName=TESTDB
  # end container
  # Volumes
volumes:
  sample:
